# Generated by Django 4.0.6 on 2022-07-31 20:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0003_board_context_alter_board_name_alter_board_owner_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moderators',
            new_name='Moderator',
        ),
    ]
