# Generated by Django 4.0.6 on 2022-07-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_rename_moderators_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
