# Generated by Django 4.0.6 on 2022-08-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_board_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
