# Generated by Django 4.0.6 on 2022-08-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_post_id_alter_thread_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='name',
            new_name='topic',
        ),
    ]
